### PR TITLE
fix(tags): tag selection modal shown when no tags can be selected

### LINKED ISSUE #3444: The tag prompt shows up even for a `0 to 0` tag requirements
## Bug Report

Discovered on Nightly by working around here: https://discuss.flarum.org/d/30939-eliminate-choose-tags-for-your-discussion-screen

**Current Behavior**
If you require 0 tag (0 to 0 for both primary & secondary), the user can post without any tag but will see the tag prompt and will have to confirm without having the possibility to select anything.

**Steps to Reproduce**
1. As admin, set both tag requirements from 0 to 0 for both tag requirements
2. As a user, create a new discussion and publish it
3. You have to see and validate the tag prompt for nothing

**Expected Behavior**
If tag requirements are from 0 to 0, I should be able to publish without having to see the tag prompt.

**Screenshots**
Screenshot 2022-06-01 at 22-52-33 Flarum_nightly

**Environment**
Nightly

**Possible Solution**
I think there should be a new scenario here:

`tag requirements === 0` : no prompt at all (except for admins if tags do exist)

### PR DESCRIPTION
**Pull request by SychO9**
**Fixes #3444**

**Changes proposed in this pull request:**
Checks that `maxPrimaryTags` and `maxSecondaryTags` are not nil before showing tag selection modal.

**Necessity**

- [x] Has the problem that is being solved here been clearly explained?
- [x] If applicable, have various options for solving this problem been considered?
- [x] For core PRs, does this need to be in core, or could it be in an extension?
- [x] Are we willing to maintain this for years / potentially forever?

**Confirmed**

- [x] Frontend changes: tested on a local Flarum installation.
- [x] Backend changes: tests are green (run `composer test`).
- [x] Core developer confirmed locally this works as intended.
- [x] Tests have been added, or are not appropriate here.

**Required changes:**

- [ ] Related documentation PR: (Remove if irrelevant)
- [ ] Related core extension PRs: (Remove if irrelevant)

### CODE REVIEW

File: extensions/tags/js/src/forum/addTagComposer.js [hunk 1]
```diff
@@ -62,9 +62,14 @@ export default function () {
...
-          || (chosenSecondaryTags.length < app.forum.attribute('minSecondaryTags'))
+    const minPrimaryTags = parseInt(app.forum.attribute('minPrimaryTags'));
+    const minSecondaryTags = parseInt(app.forum.attribute('minSecondaryTags'));
+    const maxPrimaryTags = parseInt(app.forum.attribute('maxPrimaryTags'));
+    const maxSecondaryTags = parseInt(app.forum.attribute('maxSecondaryTags'));
+
+    if (((!chosenTags.length && maxPrimaryTags !== 0 && maxSecondaryTags !== 0)
+          || (chosenPrimaryTags.length < minPrimaryTags)
+          || (chosenSecondaryTags.length < minSecondaryTags)
         ) && selectableTags.length) {
```
Comment (davwheat) [inline extensions/tags/js/src/forum/addTagComposer.js]: Does this not work, too? I think only removing the check that no tags are selected is enough.

```suggestion
    const minPrimaryTags = parseInt(app.forum.attribute('minPrimaryTags'));
    const minSecondaryTags = parseInt(app.forum.attribute('minSecondaryTags'));

    if (selectableTags.length && (chosenPrimaryTags.length < minPrimaryTags || chosenSecondaryTags.length < minSecondaryTags)) {
```

Comment (SychO9) [reply extensions/tags/js/src/forum/addTagComposer.js]: Sorry I forgot about this PR 😞 

Your change makes sense but it misses another scenario, the current behavior which we don't want to lose is that: If the maximum is not nil, and the user chooses no tags (with min being 0) the tag selection modal should show up because they can select something.

**Review by davwheat — APPROVED** [review]
