### PR TITLE
fix: notification subject discussion eager loading fails

### LINKED ISSUE #3778: fttb slow response time
### Current Behavior

我發現了一個BUG，當我的通知數來到5000+，fttb時間會來到2秒以上，但如果我清除了所有通知，則會恢復到400MS

我的母語是中文，擔心使用翻譯軟體會有差異，所以在這裡附上中文說明
My native language is Chinese, I am worried that there will be differences when using translation software, so I attach a Chinese explanation here

I found a bug where the fttb (first time to byte) time would exceed 2 seconds when my notification count reached 10000+. However, if I cleared all notifications, the fttb time would return to 400ms.

### Steps to Reproduce

Number of account notifications 5000+

### Expected Behavior

Slow initial server response time

### Screenshots

_No response_

### Environment

- Flarum version: 1.7.2
- Webserver: nginx
- Hosting environment: dedicated server
- PHP version: 8.1.7
- Browser: Chrome

### Output of `php flarum info`

```
Output of "php flarum info", run this in terminal in your Flarum directory.
```

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by SychO9**
**Closes #3778**

**Changes proposed in this pull request:**
In 1.7 the `property_exists` check was added to fix PHP 8.2 deprecations but missed the fact that dynamic properties cannot be checked like that.

I don't believe this is the problem described in the issue however, only 10 notifications are loaded at a time. So it could be a bad extension.

**Necessity**

- [x] Has the problem that is being solved here been clearly explained?
- [x] If applicable, have various options for solving this problem been considered?
- [x] For core PRs, does this need to be in core, or could it be in an extension?
- [x] Are we willing to maintain this for years / potentially forever?

**Confirmed**

- [ ] Frontend changes: tested on a local Flarum installation.
- [ ] Backend changes: tests are green (run `composer test`).
- [ ] Core developer confirmed locally this works as intended.
- [ ] Tests have been added, or are not appropriate here.

### CODE REVIEW

File: framework/core/src/Api/Controller/ListNotificationsController.php [hunk 1]
```diff
@@ -113,16 +113,16 @@ private function loadSubjectDiscussions(array $notifications)
         $ids = [];
 
         foreach ($notifications as $notification) {
-            if ($notification->subject && property_exists($notification->subject, 'discussion_id')) {
-                $ids[] = $notification->subject->discussion_id;
+            if ($notification->subject && $notification->subject->getAttribute('discussion_id')) {
```
Comment (askvortsov1) [inline framework/core/src/Api/Controller/ListNotificationsController.php]: Could we use `&& ($discussionId = $notification->subject->getAttribute('discussion_id'))` to avoid repeating it?

**Review by askvortsov1 — APPROVED** [review]
