### PR TITLE
fix(tags): not all tags are loaded in the permission grid

### LINKED ISSUE #3800: Permission grid doesn't show all the tags
### Current Behavior

If you have many tags, the permission grid tag restrictions are incomplete. When you click "Restrict by tag", you'll only see a few tags (12 in my case). If you already have a restriction for a tag that doesn't get loaded, you won't see the column in the grid at all.

### Steps to Reproduce

I don't have precise reproduction steps, but you should try to:

- Create many tags so that they go beyond the limit of tags that are loaded in the frontend automatically (it's 12 here but I can't find that number in the source code).
- Navigate to the Permissions page in the admin, refresh the page and see that if you click "Restrict by tag" some tags are missing.
- Navigate to the Tags page so that the full tags list is loaded in the store, go back to Permissions and see that the complete list is now available.

### Expected Behavior

All tags should be loaded.

### Screenshots

_No response_

### Environment

- Flarum version: 1.7.2

### Output of `php flarum info`

I can provide it if relevant.

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by SychO9**
**Fixes #3800**

**Changes proposed in this pull request:**
* The code was just getting all tags from the store, this PR changes the state to make sure to consider first load.

**Necessity**

- [x] Has the problem that is being solved here been clearly explained?
- [x] If applicable, have various options for solving this problem been considered?
- [x] For core PRs, does this need to be in core, or could it be in an extension?
- [x] Are we willing to maintain this for years / potentially forever?

**Confirmed**

- [ ] Frontend changes: tested on a local Flarum installation.
- [ ] Backend changes: tests are green (run `composer test`).
- [ ] Core developer confirmed locally this works as intended.
- [ ] Tests have been added, or are not appropriate here.

**Required changes:**

- [ ] Related documentation PR: (Remove if irrelevant)
- [ ] Related core extension PRs: (Remove if irrelevant)

### CODE REVIEW

File: extensions/tags/js/src/common/states/TagListState.ts [hunk 1]
```diff
@@ -2,17 +2,27 @@ import app from 'flarum/common/app';
...
     if (unloadedIncludes.length === 0) {
       return Promise.resolve(app.store.all<Tag>('tags'));
     }
 
-    return app.store.find<Tag[]>('tags', { include: unloadedIncludes.join(',') }).then((val) => {
-      unloadedIncludes.forEach((include) => this.loadedIncludes.add(include));
+    return this.query(unloadedIncludes);
+  }
+
+  async query(includes: string[] = []): Promise<Tag[]> {
```
Comment (askvortsov1) [inline extensions/tags/js/src/common/states/TagListState.ts:21]: Should we make this protected?

**Review by askvortsov1 — APPROVED** [review]

**Review by davwheat — APPROVED** [review]
