### PR TITLE
fix(bbcode): localize quote `wrote` string

### LINKED ISSUE #3807: Hardcoded "wrote" in flarum/bbcode
### Current Behavior

Hi, I'm interested on an old issue from 'issue-archive' repository I have the same problem and I need help with this:

https://github.com/flarum/issue-archive/issues/98

I would like to translate the string "wrote" in Spanish since I migrated an old forum from phpBB to Flarum and there were many quotes.

### Steps to Reproduce

Migrate content from another CMS and check discussions with quotes.

### Expected Behavior

A way of translating the word.

### PR DESCRIPTION
**Pull request by SychO9**
**Fixes #3807**

**Changes proposed in this pull request:**
* Allows localizing the `wrote` bit of the quote bbcode.
* This PR takes into consideration previous attempts. The translated string is not cached with the renderer cache. It is resolved on new renders.

**Necessity**

- [x] Has the problem that is being solved here been clearly explained?
- [x] If applicable, have various options for solving this problem been considered?
- [x] For core PRs, does this need to be in core, or could it be in an extension?
- [x] Are we willing to maintain this for years / potentially forever?

**Confirmed**

- [ ] Frontend changes: tested on a local Flarum installation.
- [ ] Backend changes: tests are green (run `composer test`).
- [ ] Core developer confirmed locally this works as intended.
- [ ] Tests have been added, or are not appropriate here.

**Required changes:**

- [ ] Related documentation PR: (Remove if irrelevant)
- [ ] Related core extension PRs: (Remove if irrelevant)

### CODE REVIEW

File: extensions/bbcode/extend.php [hunk 1]
```diff
@@ -9,22 +9,34 @@
...
+            $config->BBCodes->addFromRepository('B');
+            $config->BBCodes->addFromRepository('I');
+            $config->BBCodes->addFromRepository('U');
+            $config->BBCodes->addFromRepository('S');
+            $config->BBCodes->addFromRepository('URL');
+            $config->BBCodes->addFromRepository('IMG');
+            $config->BBCodes->addFromRepository('EMAIL');
+            $config->BBCodes->addFromRepository('CODE');
+            $config->BBCodes->addFromRepository('QUOTE', 'default', [
+                'authorStr' => '<xsl:value-of select="@author"/> <xsl:value-of select="$L_WROTE"/>'
```
Comment (davwheat) [inline extensions/bbcode/extend.php:33]: Can the author string be part of the translation instead? Some languages might need "wrote author" instead.

**Review by davwheat — CHANGES_REQUESTED** [review]

File: extensions/bbcode/extend.php (hunk 1 above)
Comment (SychO9) [reply extensions/bbcode/extend.php:33]: I don't believe that that's possible to do.

Comment (davwheat) [reply extensions/bbcode/extend.php:33]: Unfortunate... Either way, a locale ext could override this in their extend.php anyway, so

**Review by davwheat — APPROVED** [review]

**Review by imorland — APPROVED** [review]
