### PR TITLE
fix: `isDark()` utility can receive null value

### LINKED ISSUE #3764: `isDark` throws an error and the app crashes if a color is set to `NULL` in the database
### Current Behavior

When a tag is saved in the database with the `color` column set to `NULL`, then when trying to display that tag in the UI, there will be an error as the `isDark` util will try to call `replace` on a `null` variable. The app crashes then because of this.

### Steps to Reproduce

1. Set the color column of a tag to `NULL`
2. Open that tag index page

### Expected Behavior

No error

### Environment

- Flarum version:1.7.1
- PHP version: 8.1

### PR DESCRIPTION
**Pull request by exside**
**Fixes #3764**

**Changes proposed in this pull request:**
Shouldn't be many, was mainly an edge case when there were NULL values in the db that would crash this method.

**Necessity**

- [x] Has the problem that is being solved here been clearly explained?
Well, it doesn't crash anymore =)
- [x] If applicable, have various options for solving this problem been considered?
Decided to not make the method too fancypants for performance reasons (e.g. no regex checks for valid hex colors etc.)
- [x] For core PRs, does this need to be in core, or could it be in an extension?
- [x] Are we willing to maintain this for years / potentially forever?

**Confirmed**

- [x] Frontend changes: tested on a local Flarum installation.
- [x] Backend changes: tests are green (run `composer test`).
- [x] Core developer confirmed locally this works as intended.
- [x] Tests have been added, or are not appropriate here.

**Required changes:**

- [ ] Related documentation PR: (Remove if irrelevant)
- [ ] Related core extension PRs: (Remove if irrelevant)

### CODE REVIEW

File: framework/core/js/src/common/utils/isDark.ts [hunk 1]
```diff
@@ -8,18 +8,24 @@
  * to preserve design consistency.
  */
 export default function isDark(hexcolor: string): boolean {
```
Comment (SychO9) [inline framework/core/js/src/common/utils/isDark.ts]:
```suggestion
export default function isDark(hexcolor: string | null): boolean {
```

could you also type the `textContrastClass` util the same way?

File: framework/core/js/src/common/utils/isDark.ts [hunk 2]
```diff
@@ -8,18 +8,24 @@
...
+  // return if hexcolor is undefined or shorter than 4 characters, shortest hex form is #333;
+  // decided against regex hex color validation for performance considerations
+  if (!hexcolor || hexcolor.length <= 4) {
```
Comment (SychO9) [inline framework/core/js/src/common/utils/isDark.ts]:
```suggestion
  if (!hexcolor || hexcolor.length < 4) {
```

**Review by SychO9 — CHANGES_REQUESTED** [review]
Thanks for the PR!

File: framework/core/js/src/common/utils/isDark.ts (hunk 2 above)
Comment (luceos) [reply framework/core/js/src/common/utils/isDark.ts]: Is `hexcolor` here including the `#` or not? That would make a world of difference.

Comment (SychO9) [reply framework/core/js/src/common/utils/isDark.ts]: it includes `#`

**Review by SychO9 — APPROVED** [review]

**Review by imorland — APPROVED** [review]
