### PR TITLE
fix: post mention notification errors with _no content_ subjects

### LINKED ISSUE #3492: Mentioning an event post breaks the notification panel
## Bug Report

**Current Behavior**

If a mention refers to an event post instead of a comment (probably by mistake), the generated notification breaks the notifications panel.

**Steps to Reproduce**
1. Generate an event post (e.g. rename a discussion)
2. Login with another user and mention that post by using its ID (e.g. `@"matteocontrini"#p66032` where `66032` is the ID of the post corresponding to the rename event)
3. Login with the mentioned user and observe that an exception is thrown when trying to render the notification

**Expected Behavior**
It shouldn't break for sure, but it probably shouldn't generate a notification in general.

**Screenshots**

image

image

**Environment**
- Flarum version: 1.2.1

### PR DESCRIPTION
**Pull request by SychO9**
**Fixes #3492**

**Changes proposed in this pull request:**
Just checks before using the `contentPlain` result.

**Necessity**

- [x] Has the problem that is being solved here been clearly explained?
- [x] If applicable, have various options for solving this problem been considered?
- [x] For core PRs, does this need to be in core, or could it be in an extension?
- [x] Are we willing to maintain this for years / potentially forever?

**Confirmed**

- [x] Frontend changes: tested on a local Flarum installation.
- [x] Backend changes: tests are green (run `composer test`).
- [x] Core developer confirmed locally this works as intended.
- [x] Tests have been added, or are not appropriate here.

### CODE REVIEW

File: extensions/mentions/js/src/forum/components/PostMentionedNotification.js [hunk 1]
```diff
@@ -23,6 +23,8 @@ export default class PostMentionedNotification extends Notification {
   }
 
   excerpt() {
-    return truncate(this.attrs.notification.subject().contentPlain(), 200);
+    const contentPlain = this.attrs.notification.subject().contentPlain();
+
+    return contentPlain && truncate(contentPlain, 200);
```
Comment (davwheat) [inline extensions/mentions/js/src/forum/components/PostMentionedNotification.js]: Would this be simpler, do you think? I don't want introduce any issues, like returning false, undefined, etc, and code not accounting for this.

```suggestion
    return truncate(this.attrs.notification.subject().contentPlain() || '', 200);
```

Comment (SychO9) [reply extensions/mentions/js/src/forum/components/PostMentionedNotification.js]: Yup good thinking!

**Review by davwheat — APPROVED** [review]
