### PR TITLE
fix: invalid translation key for scheduler dashboard

### LINKED ISSUE #3697: Missing translation `core.admin.status.scheduler.inactive`
### Current Behavior

The status indicators introduced in #3593 has a missing translation for `core.admin.status.scheduler.inactive`

### Steps to Reproduce

- Have a scheduled task registered
- _not_ have a cron running for `php flarum schedule:run`
- Visit admin panel
- See missing translation

### Expected Behavior

Translation should be displayed

### Screenshots

image

### Environment

- Flarum version: x.y.z
- Website URL: http://example.com
- Webserver: [e.g. apache, nginx]
- Hosting environment: [e.g. shared, vps]
- PHP version: x.y.z
- Browser: [e.g. chrome 67, safari 11]

### Output of `php flarum info`

```
Output of "php flarum info", run this in terminal in your Flarum directory.
```

### Possible Solution

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by rob006**
Fix https://github.com/flarum/framework/issues/3697

**Necessity**

- [ ] Has the problem that is being solved here been clearly explained?
- [ ] If applicable, have various options for solving this problem been considered?
- [ ] For core PRs, does this need to be in core, or could it be in an extension?
- [ ] Are we willing to maintain this for years / potentially forever?

**Confirmed**

- [ ] Frontend changes: tested on a local Flarum installation.
- [ ] Backend changes: tests are green (run `composer test`).
- [ ] Core developer confirmed locally this works as intended.
- [ ] Tests have been added, or are not appropriate here.

**Required changes:**

- [ ] Related documentation PR: (Remove if irrelevant)
- [ ] Related core extension PRs: (Remove if irrelevant)

### CODE REVIEW

File: framework/core/src/Foundation/ApplicationInfoProvider.php [hunk 1]
```diff
@@ -119,7 +119,7 @@ public function getSchedulerStatus(): string
         // If the schedule has not run in the last 5 minutes, mark it as inactive.
         return Carbon::parse($status) > Carbon::now()->subMinutes(5)
             ? $this->translator->trans('core.admin.dashboard.status.scheduler.active')
-            : $this->translator->trans('core.admin.status.scheduler.inactive');
```
Comment (luceos) [inline framework/core/src/Foundation/ApplicationInfoProvider.php:122]: It seems to be the other way around?

https://github.com/flarum/framework/blob/d8fa791d9c4077670941ac5cd0203a791fb3ec50/framework/core/locale/core.yml#L55-L63

`dashboard` should be `status`?

**Review by luceos — CHANGES_REQUESTED** [review]

File: framework/core/src/Foundation/ApplicationInfoProvider.php (hunk 1 above)
Comment (luceos) [reply framework/core/src/Foundation/ApplicationInfoProvider.php:122]: Never mind I failed seeing the addition of the word. 👍

**Comment by luceos** [comment]
Thank you, great find!
