### PR TITLE
[1.x] Conditional extender instantiation

### LINKED ISSUE #3897: [1.x] `Conditional` extender instantiates the extenders array even when the conditional is false
### Current Behavior

The `Conditional` extender instantiates provided extenders even if the associated condition is `false`. This can lead to unintended side effects, especially if the constructors of these extenders perform actions. More critically, if the extender class doesn't even exist, it will result in a fatal error due to class not being found, regardless of the condition's value.

### Steps to Reproduce

Reference a nonexistent extender class within the Conditional extender.

```php
(new Extend\Conditional())
    ->when(false, [new NonexistentExtender()]);
```

Upon execution, PHP will throw a fatal error stating that the `NonexistentExtender` class was not found, even though the condition was set to false.

### Expected Behavior

The expected behavior is that the `Conditional` extender should only attempt to instantiate and use provided extenders when the associated condition evaluates to `true`, and should completely ignore them when the condition is `false`.

### Screenshots

_No response_

### Environment

- Flarum version: x.y.z
- Website URL: http://example.com
- Webserver: [e.g. apache, nginx]
- Hosting environment: [e.g. shared, vps]
- PHP version: x.y.z
- Browser: [e.g. chrome 67, safari 11]

### Output of `php flarum info`

```
Output of "php flarum info", run this in terminal in your Flarum directory.
```

### Possible Solution

Instead of directly providing an array of extenders, wrap them in a callback, ie invokable class

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by imorland**
Addresses #3897

### CODE REVIEW

File: framework/core/src/Extend/Conditional.php [hunk 1]
```diff
@@ -52,7 +80,15 @@ public function extend(Container $container, Extension $extension = null)
...
 
             if ($condition['condition']) {
-                foreach ($condition['extenders'] as $extender) {
+                $extenders = $condition['extenders'];
+
+                if (is_string($extenders)) {
+                    $extenders = $container->call($extenders);
+                } elseif (is_callable($extenders)) {
+                    $extenders = $container->call($extenders);
+                }
```
Comment (SychO9) [inline framework/core/src/Extend/Conditional.php]: Lets merge these
```suggestion
                if (is_string($extenders) || is_callable($extenders)) {
                    $extenders = $container->call($extenders);
                }
```

**Review by SychO9 — APPROVED** [review]
